apiVersion: apps/v1 # Versi API dan jenis objek, dalam hal ini, Deployment.
kind: Deployment # Jenis objek Kubernetes yang akan dibuat, dalam hal ini Deployment.

metadata:
  name: shipping # Nama Deployment, disematkan pada pod yang dihasilkan.
  labels: # Label untuk selektor pod.
    app: shipping # Nama label app

spec:
  replicas: 1 # Jumlah replika pod yang akan dijalankan.

  selector:
    matchLabels:
      app: shipping # Menentukan selektor untuk memilih pod berdasarkan label "app: shipping"

  template:
    metadata:
      labels:
        app: shipping # Menentukan template pod yang akan diatur oleh Deployment

    spec:
      containers:
        - name: shipping # Menentukan container dalam pod dengan nama "shipping"
          image: ghcr.io/novi-adi/shipping-service:latest # Mengatur image Docker yang akan digunakan, diambil dari Github Packages
          ports: # Daftar port yang di-ekspos oleh container.
            - containerPort: 3001 # Port yang di-ekspos oleh container.
          env: # Variabel env untuk konfigurasi port.
            - name: PORT # Environtment variable untuk port aplikasi
              value: '3001' # Port 3001
            - name: AMQP_URL # Variabel env untuk URL RabbitMQ.
              value: 'amqp://guest:guest@rabbitmq:5672' # URL koneksi untuk protokol Advanced Message Queuing Protocol (AMQP) yang mengarah ke server RabbitMQ
