version: 2.1

jobs:
  karsajobs:
    docker:
      - image: golang:latest

    steps:
      - checkout

      - run:
          name: lint-dockerfile
          command: |
            curl -sL -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
            hadolint Dockerfile

      - run:
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)

      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14

      - run:
          name: Download and install docker compose
          command: |
            apk update && apk upgrade && apk add curl  
            curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64" -o ~/docker-compose  
            chmod +x ~/docker-compose  
            mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: build-app-karsajobs
          command: |
            # chmod +x build_push_image_karsajobs.sh
            # ./build_push_image_karsajobs.sh

workflows:
  version: 2
  build:
    jobs:
      - karsajobs
